### ISSUE TITLE
Broken messenger. 

### ISSUE THREAD

**Issue by PaintedCat** [DeltaNedas/anuke-logic#6]
I got crash when the messenger has been spawned. Crash report:

```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Linux x64 (amd64)
Java Version: 17.0.1
Mods: anuke-logic:1.9.4, rtfm:2.14.10, ui-lib:2.16.6

rhino.EvaluatorException: Java class "mindustry.type.UnitType" has no public instance field or method named "outlineSpace". (messenger#29)
        at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
        at rhino.Context.reportRuntimeError(Context.java:756)
        at rhino.Context.reportRuntimeError(Context.java:802)
        at rhino.Context.reportRuntimeError2(Context.java:776)
        at rhino.JavaMembers.reportMemberNotFound(JavaMembers.java:755)
        at rhino.NativeJavaClass.get(NativeJavaClass.java:91)
        at rhino.ScriptableObject.getProperty(ScriptableObject.java:2135)
        at rhino.ScriptRuntime.getObjectProp(ScriptRuntime.java:1424)
        at rhino.ScriptRuntime.getObjectProp(ScriptRuntime.java:1418)
        at rhino.gen.messenger_17._c_anonymous_2(messenger:29)
        at rhino.gen.messenger_17.call(messenger)
        at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
        at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
        at rhino.gen.messenger_17.call(messenger)
        at rhino.JavaAdapter.doCall(JavaAdapter.java:489)
        at rhino.JavaAdapter.callMethod(JavaAdapter.java:471)
        at adapter9.draw(<adapter>)
        at mindustry.gen.UnitEntity.draw(UnitEntity.java:2035)
        at mindustry.entities.EntityGroup.lambda$draw$0(EntityGroup.java:86)
        at mindustry.entities.EntityGroup.each(EntityGroup.java:70)
        at mindustry.entities.EntityGroup.draw(EntityGroup.java:83)
        at mindustry.core.Renderer.draw(Renderer.java:320)
        at mindustry.core.Renderer.update(Renderer.java:183)
        at arc.ApplicationCore.update(ApplicationCore.java:37)
        at mindustry.ClientLauncher.update(ClientLauncher.java:177)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

**Comment by deltanedas** [comment]
ok

**Comment by deltanedas** [comment]
ok its fixed but now i gotta fix funny thing with turning
